# Database connection for Postgres 18
spring.datasource.url=jdbc:postgresql://localhost:5432/advpro-2024
spring.datasource.username=postgres
spring.datasource.password=

# Hibernate / JPA settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true